CMP_APPLY       ?= 0
DEBUG           ?= 0
GPUEn           ?= 1
CPUEn           ?= 1
CPU_INV         ?= 0
GPU_PART        ?= 0.6
CPU_PART        ?= 0.6
USE_STREAM      ?= 1
P_INTERSECT     ?= 0.0
# BANK_PART == 1 does partitioned accesses
BANK_PART       ?= 0
CMP_TYPE        ?= COMPRESSED
LOG_TYPE        ?= VERS
PROFILE         ?= 0
OLD_BMAP_IMPL   ?= 0

### BENCH can be BANK or MEMCD

BENCH           ?= BANK

DISABLE_PRSTM   ?= 0
INST_CPU        ?= 1

### IMPORTANT: for MEMCD this must be configured (e.g., PR_MAX_RWSET_SIZE=16)!!!
PR_MAX_RWSET_SIZE ?= 2
DEFAULT_blockNum  ?=
DEFAULT_threadNum ?=

SYS_CPU_MAX_FREQ=$(shell cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq)
SYS_CPU_NB_CORES=$(shell cat /proc/cpuinfo | grep processor | wc -l)

DEFINES += -DLOG_TYPE=$(LOG_TYPE) \
	-DHETM_GPU_EN=$(GPUEn) \
	-DHETM_CPU_EN=$(CPUEn) \
	-DCPU_INV=$(CPU_INV) \
	-DGPU_PART=$(GPU_PART) \
	-DCPU_PART=$(CPU_PART) \
	-DP_INTERSECT=$(P_INTERSECT) \
	-DBANK_PART=$(BANK_PART) \
	-DSYS_CPU_MAX_FREQ=$(SYS_CPU_MAX_FREQ) \
	-DPR_MAX_RWSET_SIZE=$(PR_MAX_RWSET_SIZE) \
	-DSYS_CPU_NB_CORES=$(SYS_CPU_NB_CORES) \
#

ifeq ($(OLD_BMAP_IMPL),1)
DEFINES += -DHETM_OLD_BMAP_IMPL
endif

ifeq ($(DISABLE_PRSTM),1)
DEFINES += -DBANK_DISABLE_PRSTM
endif

ifeq ($(BENCH),BANK)
DEFINES += -DBENCH_BANK
endif

ifeq ($(BENCH),MEMCD)
DEFINES += -DBENCH_MEMCD
endif

ifeq ($(CMP_APPLY),1)
DEFINES += -DCMP_APPLY=1
endif

ifeq ($(INST_CPU),1)
  DEFINES += -DHETM_INSTRUMENT_CPU
endif

############
### CMP_TYPE
ifeq ($(CMP_TYPE),COMPRESSED)
DEFINES += -DHETM_CMP_TYPE=1
endif
ifeq ($(CMP_TYPE),EXPLICIT)
DEFINES += -DHETM_CMP_TYPE=2
endif
ifeq ($(CMP_TYPE),DISABLED)
DEFINES += -DHETM_CMP_TYPE=0
endif
############

############
### LOG_TYPE
ifeq ($(LOG_TYPE),VERS)
DEFINES += -DHETM_LOG_TYPE=1
endif
ifeq ($(LOG_TYPE),ADDR)
DEFINES += -DHETM_LOG_TYPE=2
endif
ifeq ($(LOG_TYPE),BMAP)
DEFINES += -DHETM_LOG_TYPE=3
endif
ifeq ($(LOG_TYPE),VERS2)
DEFINES += -DHETM_LOG_TYPE=4
endif
############

ifeq ($(PROFILE),1)
DEFINES += -DUSE_NVTX
LIBS += -lnvToolsExt
endif

ifeq ($(USE_STREAM),1)
DEFINES += -DUSE_STREAM=1
endif

ifeq ($(DEBUG),1)
DEFINES += -DDEBUG
endif
