#!/bin/bash

DURATION=20000
SAMPLES=5
#./makeTM.sh

CPU_THREADS=4
LOW_CPU_THREADS=10
HIGH_CPU_THREADS=20

rm -f Bank.csv

# sleep 3h

function actualRun {
	timeout 50s ./bank -n $CPU_THREADS -b 640 -x 256 -a $DATASET -d $DURATION \
		-R 0 -S 16 -l ${1} -N 1 -T 32 CPU_BACKOFF=180
	if [ $? -ne 0 ]
	then
		timeout 50s ./bank -n $CPU_THREADS -b 640 -x 256 -a $DATASET -d $DURATION \
			-R 0 -S 16 -l ${1} -N 1 -T 32 CPU_BACKOFF=180
	fi
	if [ $? -ne 0 ]
	then
		timeout 50s ./bank -n $CPU_THREADS -b 640 -x 256 -a $DATASET -d $DURATION \
			-R 0 -S 16 -l ${1} -N 1 -T 32 CPU_BACKOFF=180
	fi
	if [ $? -ne 0 ]
	then
		timeout 50s ./bank -n $CPU_THREADS -b 640 -x 256 -a $DATASET -d $DURATION \
			-R 0 -S 16 -l ${1} -N 1 -T 32 CPU_BACKOFF=180
	fi
	if [ $? -ne 0 ]
	then
		timeout 50s ./bank -n $CPU_THREADS -b 640 -x 256 -a $DATASET -d $DURATION \
			-R 0 -S 16 -l ${1} -N 1 -T 32 CPU_BACKOFF=180
	fi
	if [ $? -ne 0 ]
	then
		timeout 50s ./bank -n $CPU_THREADS -b 640 -x 256 -a $DATASET -d $DURATION \
			-R 0 -S 16 -l ${1} -N 1 -T 32 CPU_BACKOFF=180
	fi
	if [ $? -ne 0 ]
	then
		timeout 50s ./bank -n $CPU_THREADS -b 640 -x 256 -a $DATASET -d $DURATION \
			-R 0 -S 16 -l ${1} -N 1 -T 32 CPU_BACKOFF=180
	fi
	if [ $? -ne 0 ]
	then
		timeout 50s ./bank -n $CPU_THREADS -b 640 -x 256 -a $DATASET -d $DURATION \
			-R 0 -S 16 -l ${1} -N 1 -T 32 CPU_BACKOFF=180
	fi
}

function doRunLargeDTST {
	# Seq. access, 18 items, prob. write {5..95}, writes 1%
	for s in `seq 1 $SAMPLES`
	do
		# -n $CPU_THREADS -b 1024 -x 512 ---> changed to single threaded
		actualRun 1
		actualRun 10
		actualRun 25
		actualRun 50
		actualRun 75
		actualRun 90
		actualRun 100
		mv Bank.csv ${1}${s}
	done
}

### Fixed the amount of CPU threads
CPU_THREADS=14

############### LARGE
###########################################################################
DATASET=250000000

############### GPU-only
make clean ; make CMP_TYPE=DISABLED USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 GPU_PART=0.55 \
	CPU_PART=0.55 P_INTERSECT=0.00 CPUEn=0 BANK_PART=1 PROFILE=1 -j 14 >/dev/null
doRunLargeDTST GPUonly_rand_sep_DISABLED_s

############## CPU-only
make clean ; make INST_CPU=0 GPUEn=0 USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
		BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 >/dev/null
doRunLargeDTST CPUonly_rand_sep_DISABLED_s

############## VERS

make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
	LOG_SIZE=4096 STM_LOG_BUFFER_SIZE=1 >/dev/null
doRunLargeDTST VERS_1x4k_s

# make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
# 	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
# 	LOG_SIZE=4096 STM_LOG_BUFFER_SIZE=2 >/dev/null
# doRunLargeDTST VERS_2x4k_s

make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
	LOG_SIZE=4096 STM_LOG_BUFFER_SIZE=4 >/dev/null
doRunLargeDTST VERS_4x4k_s

# make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
# 	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
# 	LOG_SIZE=4096 STM_LOG_BUFFER_SIZE=8 >/dev/null
# doRunLargeDTST VERS_8x4k_s

make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
	LOG_SIZE=4096 STM_LOG_BUFFER_SIZE=16 >/dev/null
doRunLargeDTST VERS_16x4k_s

###

make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
	LOG_SIZE=32768 STM_LOG_BUFFER_SIZE=1 >/dev/null
doRunLargeDTST VERS_1x32k_s

# make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
# 	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
# 	LOG_SIZE=32768 STM_LOG_BUFFER_SIZE=2 >/dev/null
# doRunLargeDTST VERS_2x32k_s

make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
	LOG_SIZE=32768 STM_LOG_BUFFER_SIZE=4 >/dev/null
doRunLargeDTST VERS_4x32k_s

# make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
# 	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
# 	LOG_SIZE=32768 STM_LOG_BUFFER_SIZE=8 >/dev/null
# doRunLargeDTST VERS_8x32k_s

make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
	LOG_SIZE=32768 STM_LOG_BUFFER_SIZE=16 >/dev/null
doRunLargeDTST VERS_16x32k_s

###

make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
	LOG_SIZE=131072 STM_LOG_BUFFER_SIZE=1 >/dev/null
doRunLargeDTST VERS_1x128k_s

# make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
# 	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
# 	LOG_SIZE=131072 STM_LOG_BUFFER_SIZE=2 >/dev/null
# doRunLargeDTST VERS_2x128k_s

make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
	LOG_SIZE=131072 STM_LOG_BUFFER_SIZE=4 >/dev/null
doRunLargeDTST VERS_4x128k_s

# make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
# 	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
# 	LOG_SIZE=131072 STM_LOG_BUFFER_SIZE=8 >/dev/null
# doRunLargeDTST VERS_8x128k_s

make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
	LOG_SIZE=131072 STM_LOG_BUFFER_SIZE=16 >/dev/null
doRunLargeDTST VERS_16x128k_s

###########################################################################

############### SMALL
###########################################################################
DATASET=25000000

############### GPU-only

make clean ; make CMP_TYPE=DISABLED USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 GPU_PART=0.55 \
	CPU_PART=0.55 P_INTERSECT=0.00 CPUEn=0 BANK_PART=1 PROFILE=1 -j 14 >/dev/null
doRunLargeDTST GPUonly_rand_sep_DISABLED_SMALL_s

############## CPU-only
make clean ; make INST_CPU=0 GPUEn=0 USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
		BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 >/dev/null
doRunLargeDTST CPUonly_rand_sep_DISABLED_SMALL_s

############## VERS

make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
	LOG_SIZE=4096 STM_LOG_BUFFER_SIZE=1 >/dev/null
doRunLargeDTST VERS_1x4k_SMALL_s

# make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
# 	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
# 	LOG_SIZE=4096 STM_LOG_BUFFER_SIZE=2 >/dev/null
# doRunLargeDTST VERS_2x4k_SMALL_s

make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
	LOG_SIZE=4096 STM_LOG_BUFFER_SIZE=4 >/dev/null
doRunLargeDTST VERS_4x4k_SMALL_s

# make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
# 	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
# 	LOG_SIZE=4096 STM_LOG_BUFFER_SIZE=8 >/dev/null
# doRunLargeDTST VERS_8x4k_SMALL_s

make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
	LOG_SIZE=4096 STM_LOG_BUFFER_SIZE=16 >/dev/null
doRunLargeDTST VERS_16x4k_SMALL_s

###

make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
	LOG_SIZE=32768 STM_LOG_BUFFER_SIZE=1 >/dev/null
doRunLargeDTST VERS_1x32k_SMALL_s

# make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
# 	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
# 	LOG_SIZE=32768 STM_LOG_BUFFER_SIZE=2 >/dev/null
# doRunLargeDTST VERS_2x32k_SMALL_s

make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
	LOG_SIZE=32768 STM_LOG_BUFFER_SIZE=4 >/dev/null
doRunLargeDTST VERS_4x32k_SMALL_s

# make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
# 	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
# 	LOG_SIZE=32768 STM_LOG_BUFFER_SIZE=8 >/dev/null
# doRunLargeDTST VERS_8x32k_SMALL_s

make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
	LOG_SIZE=32768 STM_LOG_BUFFER_SIZE=16 >/dev/null
doRunLargeDTST VERS_16x32k_SMALL_s

###

make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
	LOG_SIZE=131072 STM_LOG_BUFFER_SIZE=1 >/dev/null
doRunLargeDTST VERS_1x128k_SMALL_s

# make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
# 	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
# 	LOG_SIZE=131072 STM_LOG_BUFFER_SIZE=2 >/dev/null
# doRunLargeDTST VERS_2x128k_SMALL_s

make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
	LOG_SIZE=131072 STM_LOG_BUFFER_SIZE=4 >/dev/null
doRunLargeDTST VERS_4x128k_SMALL_s

# make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
# 	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
# 	LOG_SIZE=131072 STM_LOG_BUFFER_SIZE=8 >/dev/null
# doRunLargeDTST VERS_8x128k_SMALL_s

make clean ; make CMP_TYPE=COMPRESSED LOG_TYPE=VERS USE_TSX_IMPL=1 PR_MAX_RWSET_SIZE=20 \
	BANK_PART=1 GPU_PART=0.55 CPU_PART=0.55 P_INTERSECT=0.00 PROFILE=1 -j 14 \
	LOG_SIZE=131072 STM_LOG_BUFFER_SIZE=16 >/dev/null
doRunLargeDTST VERS_16x128k_SMALL_s

###########################################################################

mkdir -p array_prec_VERS
mv *_s* array_prec_VERS/
